### ISSUE TITLE
Tutorial.fsx error on OS X mono 4.0.2 using F# interactive v. 3.1 due to FsLab.fsx

### ISSUE THREAD

**Issue by sporring** [fslaborg/FsLab#102]
Hi, 
I just did a fresh install of FsLab.Templates-basic, and ran the Tutorial.fsx example. On my system, this caused 2 problems, firstly the warnings were displayed despite the #nowarn tag, and the DynamicInterop was not included in packages/FsLab/FsLab.fsx. For smooth running I changed the first lines in FsLab.fsx, see enclosed (to enclose, I had to change suffix from fsx to txt).
[FsLab.txt](https://github.com/fslaborg/FsLab/files/53141/FsLab.txt)
I don't know if this is a OS X/mono related issue or general.
Thanks, Jon

**Comment by vschep** [comment]
Thanks. That solved my problems, too. I am using Xamarin Studio 5.10.1 with Mono 4.2.1 and OS X 10.11.2 (El Capitan).

**Comment by tpetricek** [comment]
Sorry for the slow ping here! Can you try with the latest version of FsLab?

I added the DynamicInterop reference, so that part should work now. The warnings are a bit unfortunate :( I'm not sure why the `#nowarn` does not work - we sadly need the other paths for those referencing FsLab in Visual Studio (rather than using the much nicer simple template:))

**Comment by sporring** [comment]
Latest version seems to work. Unfortunately, it seems that WorldBankData no longer includes school enrolment information, hence Tutorial.fsx no longer works. I suggest to use the Forest data instead as (suffix changed from fsx to txt for uploading:

[Tutorial.txt](https://github.com/fslaborg/FsLab/files/110767/Tutorial.txt)

**Comment by tpetricek** [comment]
Oh no, could you send a pull request changing the indicator? Forest data sounds good :)

**Comment by sporring** [comment]
Hi Tomas,

I’m still fan of svn and a Git newbie. I’m not sure, what it is that you are asking me to do. I thought pull was the command  to copy from the server to my local copy?

Best, Jon

On 30 Jan 2016, at 17:42, Tomas Petricek <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh no, could you send a pull request changing the indicator? Forest data sounds good :)

**Comment by tpetricek** [comment]
The GitHub terminology may be confusing :-) The workflow is:

 - You _fork_  a repo using the Fork button on its home page https://github.com/fslaborg/FsLab
 - This creates your own copy of the repo that you can _clone_ on your machine
 - You do changes, _commit_ the change and _push_ to your remote clone on GitHub
 - You can then send _pull request_ to the original repo (with your fixes) that the owner of the main repo can review and accept (_merge_).

There is some more info here: https://guides.github.com/activities/contributing-to-open-source/ Let me know if you need more help!
