### ISSUE TITLE
Chart.Scatter of integers only plots first 10 points in list

### ISSUE THREAD

**Issue by sporring** [fslaborg/FsLab#103]
Hi,

I'm not sure if this is the correct place to report the following: When I use Chart.Scatter on a list of integer pairs, then only the first 10 points are plottet. For doubles, all points are plottet. E.g., the code below only plots 10 points, but if the double version is used, then all 15 points are plottet:
```
#load "packages/FsLab/FsLab.fsx"
open System
open XPlot.GoogleCharts
let rnd = new System.Random()
let data = [for i in 1 .. 15 -> (rnd.Next(10),rnd.Next(10))]
//let data = [for i in 1 .. 15 -> (rnd.NextDouble (),rnd.NextDouble ())]
Chart.Scatter data
```
I'm using Mono version 4.2, and F# 4.0, and I'm not sure how to report the version of FsLab, but I have a FsLab.0.3.10.nupkg file in the package directory and it was installed 2 weeks ago.

Thanks, Jon

**Comment by TahaHachana** [comment]
Hi,

With the max value set to 10 (only 11 possible outcomes) some data points end up having the same x and y values thus they are plotted on top of each other.

**Comment by sporring** [comment]
That would be a weird coincidence or point to an error in Random.Next (), since it is 10 no matter how many points I tried, and also since it is 2d, så there are 10*10=100 different possible outcomes. E.g.

> let points = [for i in 1..15 -> (rnd.Next(10), rnd.Next(10))];;
val points : (int * int) list =
  [(6, 9); (0, 8); (4, 4); (0, 4); (8, 4); (2, 6); (9, 2); (1, 3); (1, 5);
   (9, 3); (1, 2); (3, 0); (0, 5); (9, 3); (0, 8)]
> List.sort points;;
val it : (int * int) list =
  [(0, 4); (0, 5); (0, 8); (0, 8); (1, 2); (1, 3); (1, 5); (2, 6); (3, 0);
   (4, 4); (6, 9); (8, 4); (9, 2); (9, 3); (9, 3)]

There are reoccurrence: [(0, 8); (9, 3)] but not 5.

Best, Jon

On 09 Dec 2015, at 18:27, Taha Hachana <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

With the max value set to 10 (only 11 possible outcomes) some data points end up having the same x and y values thus they are plotted on top of each other.

**Comment by tpetricek** [comment]
Sounds like there might be something somewhere making sure that there is only one Y value for each X value?

**Comment by tpetricek** [comment]
I just checked and calling:

    let rnd = new System.Random(0)
    let data = [for i in 1 .. 1000 -> (rnd.Next(10),rnd.Next(10))]
    Chart.Scatter data

Generates:

    var data = new google.visualization.DataTable({"cols": [{"type": "number" ,"id": "Column 1" ,"label": "Column 1" }, {"type": "number" ,"id": "Column 2" ,"label": "Column 2" }], "rows" : [{"c" : [{"v": 7}, {"v": 8}]}, {"c" : [{"v": 2}, {"v": 5}]}, {"c" : [{"v": 9}, {"v": 4}]}, {"c" : [{"v": 6}, {"v": 4}]}, {"c" : [{"v": 8}, {"v": 9}]}, {"c" : [{"v": 5}, {"v": 0}]}, {"c" : [{"v": 1}, {"v": 4}]}, {"c" : [{"v": 0}, {"v": 3}]}, {"c" : [{"v": 3}, {"v": 9}]}, {"c" : [{"v": 4}, {"v": 7}]}]});

So it sounds like XPlot is somehow (accidentally?) getting only one Y value for each X value.

**Comment by TahaHachana** [comment]
I managed to reproduce this issue after updating my FsLab installation. I'll fix it in the next release.

**Comment by sporring** [comment]
Great and thank you. Jon

On 11 Dec 2015, at 17:37, Taha Hachana <notifications@github.com<mailto:notifications@github.com>> wrote:


I managed to reproduce this issue after updating my FsLab installation. I'll fix it in the next release.
