### ISSUE TITLE
FsLab Journal template does not compile

### ISSUE THREAD

**Issue by eknutsen3** [fslaborg/FsLab#104]
I just downloaded the FSlab journal template from fslab.org.  when I try to run the tutorial.fsx I get a number of errors in the build.fsx.  These errors seem to be specific to the suave library. 
The first issue is “open Suave.HTTP.Files” apparently there is no Files namespace.
The script uses an UTF8 data type that cannot be found.
The script also uses an Applicatives type that cannot be found.

Looking at Suave in GitHub it looks like Suave.HTTP.Files was depreciated.  Using Suave.Files as suggested in the obsolete note does not fix the issues above.

**Comment by hckmd** [comment]
Hi. 
I ran into the same issue. As a temporary workaround I specified the version of Suave in the paket.dependencies to be 0.33.0, updated the solution's packages, and the journal built and ran ok. 

Sorry I can't help more, but I am new to F# and haven't used Suave before. It looks like the changes in the latest release of Suave will mean the build.fsx file will need to be updated.

**Comment by eknutsen3** [comment]
Yes, Suave 1.0 has a number of breaking changes.  I opened an issue with FsLab.Template as that is more appropriate for this issue.
