### ISSUE TITLE
FsLab Journal Template doesn't build

### ISSUE THREAD

**Issue by genechiaramonte** [fslaborg/FsLab#106]
I downloaded the FsLab Journal Template, installed it in VS2013 Community Edition and created a new FsLab project. When I build the default project I get the following error: "build.fsx(42,17): error FS0039: The namespace 'Files' is not defined"

**Comment by tpetricek** [comment]
Is that from the VS gallery? That's probably the same issue as #104! Can you use the download from www.fslab.org instead? http://fslab.org/download/

**Comment by tpetricek** [comment]
I just released a new version where things should work. Can you remove the VS template, download it again and check things? If it still fails, please reopen the issue.

**Comment by genechiaramonte** [comment]
Tomas,

I've downloaded the new version and it builds and runs correctly. Many thanks updating the template. FsLab is great!

Gene
