### ISSUE TITLE
Error: Evaluating F# snippet failed

### ISSUE THREAD

**Issue by genechiaramonte** [fslaborg/FsLab#107]
Hi,

I get the following error (screen shot attached) and then the .fsx file evaluated and the generated html files all look fine. Any idea what might be causing this or how I could track down the problem?

Thanks,

Gene

![screenshot 337](https://cloud.githubusercontent.com/assets/16423061/12532073/fba6af88-c1e0-11e5-88e3-034af45573a9.png)

**Comment by tpetricek** [comment]
I think you can break the script in this way if you redefine some global standard F# name somewhere in your script. For example if you did:

    (*** hide ***)
    let Some a = 0
    #load "packages/FsLab/FsLab.fsx"

Are you by any chance hiding some global value that is used in the `FsLab.fsx` script on line 83?

**Comment by tpetricek** [comment]
I'd need more detailed repro in order to be able to look into that - for now, I'm closing this, but feel free to reopen if you can share detailed repro steps.
