### ISSUE TITLE
Never ending dependencies problem when installing (first time) FSLAB from Nuget

### ISSUE THREAD

**Issue by RaulHomburg** [fslaborg/FsLab#110]
Hi, 

This is my first post and I am very new to F#. I have spent 2 days trying to resolve the never ending "Rolls backs" from Nuget Installation package. I had problems with inconsistent Deedle.RProvider, NewtonSoft.Json version, etc.  Somehow each one I have managed to solve. 

The following though, seems impossible: **_"Install-Package : Could not install package 'XPlot.Plotly 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0"_**

Does anyone have a solution / work around for it? I am working with Visual Studio 2010, on a regular PC with Windows 7. I do not have admin rights but this is not the problem (or i dont believe this is the problem). 

The frustrating part is that I cannot even test a simple script until all modules load, although many of them I dont need them, specially all those related to R. Is there a way to installed a customized version?

Install-Package : Could not install package 'XPlot.Plotly 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.At line:1 char:1
+ Install-Package XPlot.Plotly -version 1.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by tpetricek** [comment]
I'll have a look to see if we need to update dependencies. NuGet is unfortunately quite sensitive to this (even though FsLab has a fixed version dependency on everything - it is quite silly).

In the meantime, can you try downloading the template from: http://fslab.org/download/

This uses Paket for dependency manager (just follow the instructions on the left), which is way more predictable and reproducible.

**Comment by tpetricek** [comment]
Should be fixed in 0.3.18 (and newer). Thanks for reporting this!
