### ISSUE TITLE
Things to do before 1.0 release

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/FsLab#112]
Definitely needs to be done 
- [x] Recover Math.NET formatting support
- [x] XPlot Plotly support
- [x] F# Charting support (and saving `Image` objects generally)
- [x] Update "Walkthrough" to use XPlot & test Math.NET 
- [x] Update Journal template (to include `#load` Style)

Possibly (these might be tricky):
- [ ] Recover LaTeX support
- [ ] Recover R provider formatting support 
- [ ] Update "Walkthrough with R"

**Comment by tpetricek** [comment]
Math.NET:  https://github.com/fslaborg/FsLab.Formatters/commit/a847f6225f067c9148b62c36ff7d8f570e407518

**Comment by tpetricek** [comment]
F# Charting + Images: https://github.com/fslaborg/FsLab.Formatters/commit/152631bcf54125c335d401b3291c5cd054f4aa4d

**Comment by tpetricek** [comment]
Moving LaTeX to later - this is not really the most essential thing and it'll be more work.

**Comment by tpetricek** [comment]
Plotly: https://github.com/fslaborg/FsLab.Formatters/commit/ab6ed1e69b27fe727c273bef6e0b212c7f111b3d

**Comment by dsyme** [comment]
@tpetricek THe 1.0 release has been made - can we close this? thanks
