### ISSUE TITLE
Problems to display charts in ionide + atom

### ISSUE THREAD

**Issue by EdouardM** [fslaborg/FsLab#114]
Hello i am trying to display one chart with FsLab grabbed with paket. 

I am using ionide on Atom. I use FSharp.Charting library with code like with (surfaces: float list):

let ch = Chart.Histogram surfaces
ch.ShowChart()

The window with the graph opens very briefly and disappears. 

I have an output in fsi: val it: System.Windows.Forms.Form, Text = Column Chart (xx)

I am using
ionide v.1.9.1
ionide fsi v.2.1.3
FsLab 0.3.20

**Comment by tpetricek** [comment]
Thanks for reporting this! I think it is the same as: https://github.com/ionide/FsInteractiveService/issues/10 I'm looking into that.

**Comment by EdouardM** [comment]
Hello Tomas, 

Thanks for the quick reply. Indeed the issue is more general and concerns forms. 
I tried to display a new form from within FSI and it failed the same way as the chart. 

Regards;
Edouard

**Comment by EdouardM** [comment]
Tomas,

I saw on twitter you were able to embed graphs in FSI while using Atom. That's what I was trying to obtain. 

Do you have guidelines on how to achieve this ?

Thanks,
Edouard

**Comment by tpetricek** [comment]
@EdouardM That was using the XPlot library, most recent pre-release version of FsLab. It should work with current release or Ionide, though there are still some bugfixes that need to be merged.

(So, it's all getting close, but if you can wait one more week, it should all be much smoother :-))

**Comment by EdouardM** [comment]
Hi Tomas, 

Thanks for sharing the trick but it is definitely too complicated for me. I can wait one week, no worries! 
F# tooling is about to become so great! 

Many thanks,
Edouard

**Comment by tpetricek** [comment]
The latest version supports embedding of F# Charts in Atom, so all should be good now.
