### ISSUE TITLE
CsvProvider error with FsLab

### ISSUE THREAD

**Issue by cechovsky** [fslaborg/FsLab#115]
I have project where I used CsvProvider from FSharp.Data.dll

```
#r "packages/FSharp.Data/lib/net40/FSharp.Data.dll"
open FSharp.Data
type Result = CsvProvider<"C:/data.txt", ";", HasHeaders=true, IgnoreErrors=true>
let data1 = Result.Load("C:/data.txt");
```

This code worked but now I tried to use FsLab.fsx to load all libraries for working with data. I use following code.

```
#load "packages/FsLab/FsLab.fsx"
open FSharp.Data
type Result = CsvProvider<"C:/data.txt", ";", HasHeaders=true, IgnoreErrors=true>
let data1 = Result.Load("C:/data.txt");
```

But this code returns error

> error FS3033: The type provider 'ProviderImplementation.CsvProvider' reported an error in the context of provided type 'FSharp.Data.CsvProvider,Sample="C:/data.txt",Separators=";",IgnoreErrors="True"', member 'Load'. The error: Exception of type 'System.Collections.Generic.KeyNotFoundException' was thrown.

When I try this approach

```
#load "packages/FsLab/FsLab.fsx"
open FSharp.Data
type Result = CsvProvider<"C:/data.txt", ";", HasHeaders=true, IgnoreErrors=true>
let data1 = new Result()
```

I get another error
The type provider 'ProviderImplementation.CsvProvider' reported an error in the context of provided type 'FSharp.Data.CsvProvider,Sample="C:/data.txt",Separators=";",IgnoreErrors="True"', member '.ctor'. The error: The given key was not present in the dictionary.

As I see in the FsLab.fsx script file, FSharp.Data.dll is loaded there. How can I fix this issue?

**Comment by tpetricek** [comment]
This should be fixed in F# Data 2.3.1. Please report back if you keep seeing errors!
