### ISSUE TITLE
Should allow running individual script

### ISSUE THREAD

**Issue by kflu** [fslaborg/FsLab#116]
Right now for the FsLab Journal, I ran `build run` to serve up the web page. If I have more than one scripts at the project root, the command processes all scripts at once.

This behavior is undesirable for the scenario where I have one such fslab journal project containing a bunch of scripts, as I add new script over the years. Yet I don't care about the output of the previously written scripts, but just the one that I'm currently writing. For that, I need a command that allow me to **just** process a single script at my choice. Is this possible? Or how should I go about it?

**Comment by ArtemyB** [comment]
@kflu don't know if this question is still relevant for you, but I also had it recently. Fortunately FsLab already supports such feature. So I'll provide an answer there for others, who will face same problem. There is a [`FileWhitelist`][1] field in the `FsLab.ProcessingContext` record type for specifying what files should be processed.

[1]: https://github.com/fslaborg/FsLab/blob/master/src/FsLab.Runner/Config.fs#L25

**Comment by tpetricek** [comment]
Thanks for the answer @ArtemyB !
