### ISSUE TITLE
FsLab Journal memory leak and eventually OutOfMemoryException

### ISSUE THREAD

**Issue by kflu** [fslaborg/FsLab#121]
![fslab_mem](https://cloud.githubusercontent.com/assets/1031978/20419415/0722004a-ad0b-11e6-806a-9029817d83b5.png)

When in the `build.cmd run` mode, everytime I make a change to the script, `FAKE`'s memory increases. And eventually it goes to 1+GB and crashes with OutOfMemoryException.

**Comment by dsyme** [comment]
Thsi is by design, memory is not recycled, you just need to restart
