### ISSUE TITLE
Can't install dependencies with paket in ubuntu

### ISSUE THREAD

**Issue by xuyao0127** [fslaborg/FsLab#124]
I am using Ubuntu 16.10. After I downloaded the basic template, I use the paket tool provided in Atom Ionide package to install all dependencies. But it failed with message
`
Paket version 3.33.5
Resolving packages for group Main:
 - FsLab 1.0.2
    Package not available.
      Message: Couldn't get package details for package FsLab 1.0.2 on https://www.nuget.org/api/v2.
 - FsLab 1.0.1
    Package not available.
      Message: Couldn't get package details for package FsLab 1.0.1 on https://www.nuget.org/api/v2.
 - FsLab 1.0.0
    Package not available.
      Message: Couldn't get package details for package FsLab 1.0.0 on https://www.nuget.org/api/v2.
 - FsLab 0.3.21
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.21 on https://www.nuget.org/api/v2.
 - FsLab 0.3.20
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.20 on https://www.nuget.org/api/v2.
 - FsLab 0.3.19
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.19 on https://www.nuget.org/api/v2.
 - FsLab 0.3.18
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.18 on https://www.nuget.org/api/v2.
 - FsLab 0.3.17
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.17 on https://www.nuget.org/api/v2.
 - FsLab 0.3.16
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.16 on https://www.nuget.org/api/v2.
 - FsLab 0.3.15
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.15 on https://www.nuget.org/api/v2.
 - FsLab 0.3.14
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.14 on https://www.nuget.org/api/v2.
 - FsLab 0.3.13
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.13 on https://www.nuget.org/api/v2.
 - FsLab 0.3.12
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.12 on https://www.nuget.org/api/v2.
 - FsLab 0.3.11
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.11 on https://www.nuget.org/api/v2.
 - FsLab 0.3.10
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.10 on https://www.nuget.org/api/v2.
 - FsLab 0.3.9
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.9 on https://www.nuget.org/api/v2.
 - FsLab 0.3.8
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.8 on https://www.nuget.org/api/v2.
 - FsLab 0.3.7
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.7 on https://www.nuget.org/api/v2.
 - FsLab 0.3.6
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.6 on https://www.nuget.org/api/v2.
 - FsLab 0.3.5
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.5 on https://www.nuget.org/api/v2.
 - FsLab 0.3.4
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.4 on https://www.nuget.org/api/v2.
 - FsLab 0.3.3
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.3 on https://www.nuget.org/api/v2.
 - FsLab 0.3.2
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.2 on https://www.nuget.org/api/v2.
 - FsLab 0.3.1
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.1 on https://www.nuget.org/api/v2.
 - FsLab 0.3.0
    Package not available.
      Message: Couldn't get package details for package FsLab 0.3.0 on https://www.nuget.org/api/v2.
 - FsLab 0.2.7
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.7 on https://www.nuget.org/api/v2.
 - FsLab 0.2.6
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.6 on https://www.nuget.org/api/v2.
 - FsLab 0.2.5
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.5 on https://www.nuget.org/api/v2.
 - FsLab 0.2.4
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.4 on https://www.nuget.org/api/v2.
 - FsLab 0.2.3
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.3 on https://www.nuget.org/api/v2.
 - FsLab 0.2.2
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.2 on https://www.nuget.org/api/v2.
 - FsLab 0.2.1
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.1 on https://www.nuget.org/api/v2.
 - FsLab 0.2.0
    Package not available.
      Message: Couldn't get package details for package FsLab 0.2.0 on https://www.nuget.org/api/v2.
 - FsLab 0.1.4
    Package not available.
      Message: Couldn't get package details for package FsLab 0.1.4 on https://www.nuget.org/api/v2.
 - FsLab 0.1.3
    Package not available.
      Message: Couldn't get package details for package FsLab 0.1.3 on https://www.nuget.org/api/v2.
 - FsLab 0.1.2
    Package not available.
      Message: Couldn't get package details for package FsLab 0.1.2 on https://www.nuget.org/api/v2.
 - FsLab 0.1.1
    Package not available.
      Message: Couldn't get package details for package FsLab 0.1.1 on https://www.nuget.org/api/v2.
 - FsLab 0.1.0
    Package not available.
      Message: Couldn't get package details for package FsLab 0.1.0 on https://www.nuget.org/api/v2.
 - FsLab 0.0.19
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.19 on https://www.nuget.org/api/v2.
 - FsLab 0.0.18
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.18 on https://www.nuget.org/api/v2.
 - FsLab 0.0.17
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.17 on https://www.nuget.org/api/v2.
 - FsLab 0.0.16
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.16 on https://www.nuget.org/api/v2.
 - FsLab 0.0.15
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.15 on https://www.nuget.org/api/v2.
 - FsLab 0.0.3
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.3 on https://www.nuget.org/api/v2.
 - FsLab 0.0.2
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.2 on https://www.nuget.org/api/v2.
 - FsLab 0.0.1
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.1 on https://www.nuget.org/api/v2.
 - FsLab 0.0.0.6
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.0.6 on https://www.nuget.org/api/v2.
 - FsLab 0.0.0.5
    Package not available.
      Message: Couldn't get package details for package FsLab 0.0.0.5 on https://www.nuget.org/api/v2.
Paket failed with:
	There was a version conflict during package resolution.
  Could not resolve package FsLab:
   - Dependencies file requested package FsLab: >= 0
   - Available versions:
     - (1.0.2, [https://www.nuget.org/api/v2])
     - (1.0.1, [https://www.nuget.org/api/v2])
     - (1.0.0, [https://www.nuget.org/api/v2])
     - (0.4.10-beta, [https://www.nuget.org/api/v2])
     - (0.4.9-beta, [https://www.nuget.org/api/v2])
     - (0.4.8-beta, [https://www.nuget.org/api/v2])
     - (0.4.7-beta, [https://www.nuget.org/api/v2])
     - (0.4.6-beta, [https://www.nuget.org/api/v2])
     - (0.4.5-beta, [https://www.nuget.org/api/v2])
     - (0.4.4-beta, [https://www.nuget.org/api/v2])
     - (0.4.3-beta, [https://www.nuget.org/api/v2])
     - (0.4.2-beta, [https://www.nuget.org/api/v2])
     - (0.4.1-beta, [https://www.nuget.org/api/v2])
     - (0.4.0-beta, [https://www.nuget.org/api/v2])
     - (0.3.21, [https://www.nuget.org/api/v2])
     - (0.3.20, [https://www.nuget.org/api/v2])
     - (0.3.19, [https://www.nuget.org/api/v2])
     - (0.3.18, [https://www.nuget.org/api/v2])
     - (0.3.17, [https://www.nuget.org/api/v2])
     - (0.3.16, [https://www.nuget.org/api/v2])
     - (0.3.15, [https://www.nuget.org/api/v2])
     - (0.3.14, [https://www.nuget.org/api/v2])
     - (0.3.13, [https://www.nuget.org/api/v2])
     - (0.3.12, [https://www.nuget.org/api/v2])
     - (0.3.11, [https://www.nuget.org/api/v2])
     - (0.3.10, [https://www.nuget.org/api/v2])
     - (0.3.9, [https://www.nuget.org/api/v2])
     - (0.3.8, [https://www.nuget.org/api/v2])
     - (0.3.7, [https://www.nuget.org/api/v2])
     - (0.3.6, [https://www.nuget.org/api/v2])
     - (0.3.5, [https://www.nuget.org/api/v2])
     - (0.3.4, [https://www.nuget.org/api/v2])
     - (0.3.3, [https://www.nuget.org/api/v2])
     - (0.3.2, [https://www.nuget.org/api/v2])
     - (0.3.1, [https://www.nuget.org/api/v2])
     - (0.3.0, [https://www.nuget.org/api/v2])
     - (0.2.7, [https://www.nuget.org/api/v2])
     - (0.2.6, [https://www.nuget.org/api/v2])
     - (0.2.5, [https://www.nuget.org/api/v2])
     - (0.2.4, [https://www.nuget.org/api/v2])
     - (0.2.3, [https://www.nuget.org/api/v2])
     - (0.2.2, [https://www.nuget.org/api/v2])
     - (0.2.1, [https://www.nuget.org/api/v2])
     - (0.2.0, [https://www.nuget.org/api/v2])
     - (0.1.4, [https://www.nuget.org/api/v2])
     - (0.1.3, [https://www.nuget.org/api/v2])
     - (0.1.2, [https://www.nuget.org/api/v2])
     - (0.1.1, [https://www.nuget.org/api/v2])
     - (0.1.0, [https://www.nuget.org/api/v2])
     - (0.0.19, [https://www.nuget.org/api/v2])
     - (0.0.18, [https://www.nuget.org/api/v2])
     - (0.0.17, [https://www.nuget.org/api/v2])
     - (0.0.16, [https://www.nuget.org/api/v2])
     - (0.0.15, [https://www.nuget.org/api/v2])
     - (0.0.14-beta, [https://www.nuget.org/api/v2])
     - (0.0.13-beta, [https://www.nuget.org/api/v2])
     - (0.0.12-beta, [https://www.nuget.org/api/v2])
     - (0.0.11-beta, [https://www.nuget.org/api/v2])
     - (0.0.10-beta, [https://www.nuget.org/api/v2])
     - (0.0.9-beta, [https://www.nuget.org/api/v2])
     - (0.0.8-beta, [https://www.nuget.org/api/v2])
     - (0.0.7-beta, [https://www.nuget.org/api/v2])
     - (0.0.6-beta, [https://www.nuget.org/api/v2])
     - (0.0.5-beta, [https://www.nuget.org/api/v2])
     - (0.0.4-beta, [https://www.nuget.org/api/v2])
     - (0.0.3, [https://www.nuget.org/api/v2])
     - (0.0.2, [https://www.nuget.org/api/v2])
     - (0.0.1, [https://www.nuget.org/api/v2])
     - (0.0.1-beta, [https://www.nuget.org/api/v2])
     - (0.0.0.6, [https://www.nuget.org/api/v2])
     - (0.0.0.5, [https://www.nuget.org/api/v2])

  Please try to relax some conditions.`

**Comment by dsyme** [comment]
The problem is the SSL certificates on Ubuntu, update your certificates and make sure you can access nuget.org
