### ISSUE TITLE
From Indicator to Series

### ISSUE THREAD

**Issue by amieres** [fslaborg/FsLab#125]
I was trying to follow the tutorial, but it seems to be out of date.
Foogle does not seem to be part of FsLab anymore.

More specifically, from WorldBank.Indicator to Series the casting/convertion does not seem to happen automatically anymore. I had to invoke a function for each indicator:

```
let toSeries_ (ind: Runtime.WorldBank.Indicator) = ind.Values |> Seq.zip ind.Years |> Series.ofObservations

let fem = eu.``School enrollment, tertiary, female (% gross)`` |> toSeries

```
I do not think this was the intended use. How can this be fixed?

**Comment by tpetricek** [comment]
Which tutorial are you looking at? What was the original code you tried to run & what error did you get?

**Comment by amieres** [comment]
Is the Getting Started Tutorial:

https://fslab.org/getting-started/

`open Foogle`
says "The namespace of module Foogle is not defined"

```
abs (czschool - euschool)
|> Series.sort
|> Series.rev
|> Series.take 5
```

This line says: The type Runtime.WorldBank.Indicator does not support the operator '-'.

**Comment by irustandi** [comment]
That tutorial page seems to need updating. The tutorial that is included in the FsLab basic template pretty much does the same thing, and it's more up-to-date. In particular, Foogle has been replaced by XPlot.

**Comment by tpetricek** [comment]
I see, yes, Foogle has been deprecated & removed and it should use XPlot instead. If you wanted to help us, it would be awesome if you could send a PR - the file that needs to be updated is: https://github.com/fslaborg/fslaborg.github.io/blob/source/content/getting-started/index.fsx

**Comment by dsyme** [comment]
The page hya
