### ISSUE TITLE
MathJax CDN shutting down on April 30, 2017.

### ISSUE THREAD

**Issue by amieres** [fslaborg/FsLab#126]
Matrix printing is not working.

Need to change to: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js

**Comment by tpetricek** [comment]
Could you send a PR with a fix? I think all the occurences can be found here: https://github.com/search?q=org%3Afslaborg+mathjax&type=Code

**Comment by dsyme** [comment]
PR sent here: https://github.com/fslaborg/FSharp.Charting/pull/129

**Comment by dsyme** [comment]
Please check?
