### ISSUE TITLE
Cannot load FsLab.fsx due to RDotNet exception

### ISSUE THREAD

**Issue by suoranta** [fslaborg/FsLab#127]
Just installed FsLab latest stable with Nuget but cannot load it into F# script as 
`#load "../packages/FsLab.1.0.2/FsLab.fsx"`
causes the following error:
>The type provider 'RProvider.RProvider' reported an error: The type provider constructor has thrown an exception: Type 'RDotNet.EvaluationException' in Assembly 'RDotNet, Version=1.6.5.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

**Comment by tpetricek** [comment]
- Do you have R installed? (It should not be needed, but it's useful to know!)
 - What OS, editor and version of F# are you using?

**Comment by suoranta** [comment]
Yeah, should have included these. Windows 10, VS 2017 Professional (F# 4.0), Microsoft Open R 3.4.0 installed before VS. VS 2015 is also installed but not used for this project.

**Comment by suoranta** [comment]
I noticed that I actually had the previous version of R Open, and upgraded it to R Open 3.4.0 (uninstalling the old one). The problem seems now to be gone. Either that upgrade or the recent VS update fixed this one.

**Comment by dumnovnz** [comment]
Is this problem resolved? I've had the same. Please let me know how to get around

**Comment by suoranta** [comment]
As stated, I got around the issue with the upgrades. Can't add much to that. If you don't need RDotNet, one option is to edit FsLab.fsx so as not to load it.

**Comment by dumnovnz** [comment]
Thank you for the prompt reply. I wonder if Microsoft monitors this page.

**Comment by tpetricek** [comment]
I was not able to repro this - I created new F# Tutorial project using VS2015, added FsLab 1.0.2 via NuGet and then loaded it using `#load @"..\packages\FsLab.1.0.2\FsLab.fsx"` and everything works. I have the normal non-Microsoft R installed, version 3.4.2.
