### ISSUE TITLE
Update Getting started page code examples on fslab.org site

### ISSUE THREAD

**Issue by jbowles** [fslaborg/FsLab#133]
On this page of fslab.org [https://fslab.org/getting-started/](https://fslab.org/getting-started/) the code examples are a little out of date.

For example, `Foogle` looks like it is no longer part of the `fslabbasic` template 
   * visual studio code 2017 version ` 1.18.1`
   * mono  --version `Mono JIT compiler version 5.4.1.7 (2017-06/e66d9abbb27 Wed Oct 25 12:10:41 EDT 2017)`
   * forge --version `2.1.0`

I worked through the example and got it working using the updated Worldbank data for enrollment on tertiary gross as well as working with XPlot.

I'm more than happy to update the example and submit a PR but I don't where that would be.

Below is the updated example and a screenshot of the Xplot (Google Chart) graph.

```f#
#load "../packages/FsLab/FsLab.fsx"

open XPlot.GoogleCharts
open Deedle
open FSharp.Data

let wb = WorldBankData.GetDataContext()
let cz = wb.Countries.``Czech Republic``.Indicators
let eu = wb.Countries.``European Union``.Indicators

let czschool = series cz.``School enrollment, tertiary (gross), gender parity index (GPI)``
let euschool = series eu.``School enrollment, tertiary (gross), gender parity index (GPI)``

abs (czschool - euschool)
|> Series.sort
|> Series.rev
|> Series.take 5

let schoolDataCZ = [for y in 1985 .. 2012 -> string y, cz.``School enrollment, tertiary (gross), gender parity index (GPI)``.[y] ]
let schoolDataEU = [for y in 1985 .. 2012 -> string y, eu.``School enrollment, tertiary (gross), gender parity index (GPI)``.[y] ]

let options = 
    Options (title = "CZ and EU Tertiary Gross Enrollment")

[schoolDataCZ; schoolDataEU]
|> Chart.Line
|> Chart.WithOptions options
|> Chart.WithLabels ["CZ";"EU"]
```

<img width="693" alt="cz_eu_tertiary_enroll_gross" src="https://user-images.githubusercontent.com/356368/33806149-c4f538ca-dd80-11e7-9596-32dced23ee23.png">

**Comment by tpetricek** [comment]
Hello!
Thanks very much for looking into this - yes, Foogle is now deprecated and XPlot is the library to use. If you were able to update the sample, that would be fantastic. It is generated from this file: https://github.com/fslaborg/fslaborg.github.io/blob/source/content/getting-started/index.fsx

**Comment by jbowles** [comment]
Awesome. I'll get a PR up today.

**Comment by dsyme** [comment]
@tpetricek I had trouble updating to remove Foogle properly because the fslaborg.github.io site was using some 0.3 version of FsLab, with Formatters.fs still referring to Foogle.

I updated to latest FsLab in https://github.com/fslaborg/fslaborg.github.io/pull/15 but couldn't work out how/if to patch Formatters.fs, so for now removed the XPlot visualization. We can add it back in due course.

If you have any advice please chime in, thanks
