### ISSUE TITLE
Can't use SQLite on OSX

### ISSUE THREAD

**Issue by sergi** [fslaborg/FsLab#134]
I wrote an almost direct copy of FsLab canonical example, but modified it to use a SQLite provider. You can find it here: https://github.com/sergi/FoxStat. The main (and only) script is https://github.com/sergi/FoxStat/blob/master/FoxStats.fsx.

When I run it, I get the following error:
<code>
/.../FoxStat/FoxStats.fsx(26,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: SQLite.Interop.dll, Path: /.../FoxStat/packages/System.Data.SQLite.Core/lib/net451 (You are running on x64.)
</code>

It seems it has a problem finding `SQLite.Interop.dll`, but I've already tried copying from `packages/System.Data.SQLite.Core/build/net451/x64/SQLite.Interop.dll` (also tried with the x86 version), and it keeps giving the same message.

I am building this on OSX, by the way. After searching for it, I've found other cases of this problem, but no solution for it.

It should be easily reproducible by just cloning my project on a Mac and try to run the script `FoxStats.fsx`.

Is there a solution to this?

**Comment by tpetricek** [comment]
I think this is SQL provider related issue, so you'll probably get more help if you post it here: http://github.com/fsprojects/SQLProvider
