### ISSUE TITLE
charting, which one?

### ISSUE THREAD

**Issue by TonyAbell** [fslaborg/FsLab#71]
currently supported 

Foogle.Charts 
FSharp.Charting 

should support be added for [FnuPlot](http://fsprojects.github.io/FnuPlot/) and [FsPlot](http://tahahachana.github.io/FsPlot/)

should FsLab standardize on a single charting lib?

**Comment by tpetricek** [comment]
Currently, all of them have drawbacks. But I would certainly like to look into FsPlot.  

If you're interested in working on this, that would be great. Otherwise, I have it on my TODO list, but I'm probably going to be busy next few weeks.

**Comment by tpetricek** [comment]
We now have XPlot and FSharp.Charting.

Foogle is legacy and will get removed shortly. I think this is reasonably good situation to be in, so I'm closing this issue.
