### ISSUE TITLE
Include more F# charting libs in the package

### ISSUE THREAD

**Issue by ovatsus** [fslaborg/FsLab#83]
Besides FSharp.Charting and Foogle.Charts, also include FsPlot, XPlot, VegaHub

**Comment by dsyme** [comment]
Or remove FSharp.Charting and Foogle.Charts. 

It's tricky - is FsLab a foundation, or a combination of every package that might possibly relevant to data science?

**Comment by tpetricek** [comment]
I actually opened a thread to discuss the XPlot topic with @TahaHachana (https://github.com/TahaHachana/XPlot/issues/5). My current thinking about FsLab charting is:

 - Include XPlot and make it the default for demos
 - Remove & archive Foogle.Charts (too incomplete, replaced by XPlot)
 - Keep F# Charting (still frequently used and appears too often) but keep it in "maintain mode"
 - I'll discuss FsPlot with @TahaHachana - though I think we should pick just one and XPlot seems to be better fit (at least I think so)
 - VegaHub is interesting, but I think it is too early for it to be practically useful

**Comment by dsyme** [comment]
Sounds good :)

**Comment by tpetricek** [comment]
XPlot is now included. I'd be happy to add more libraries, if they were reasonably complete and well-documented. I think FsPlot would be potentially interesting, but it serves similar purpose as XPlot, so it might be better to keep just one of the two for now.
