### ISSUE TITLE
References are a little out of sync from the nuget package

### ISSUE THREAD

**Issue by monkieboy** [fslaborg/FsLab#90]
I was going through the http://fslab.org/getting-started/ page but found that the FsLab references in the FsLab.fsx were not pointed to the right dependencies:

#I "../XPlot.Plotly.1.0.1/lib/net45" should be #I "../XPlot.Plotly.1.0.1.0/lib/net45"

#I "../XPlot.GoogleCharts.1.1.7/lib/net45" should be #I "../XPlot.GoogleCharts.1.1.7.0/lib/net45"
this should be removed: #I "../XPlot.GoogleCharts.Deedle/lib/net45"

#I "../XPlot.GoogleCharts.Deedle.0.6.2/lib/net45" should be #I "../XPlot.GoogleCharts.Deedle.0.6.2.0/lib/net45"

this should be removed: #I "../Google.DataTable.Net.Wrapper/lib"

#I "../Google.DataTable.Net.Wrapper.3.1.2/lib" should be #I "../Google.DataTable.Net.Wrapper.3.1.2.0/lib"

I wanted to create a pull request to make the change but not sure if this file is generated?

**Comment by tpetricek** [comment]
This was fixed via https://github.com/fslaborg/FsLab/commit/2475145d2181d9e588ddd43cf8ecbd932c6c8a1c
