### ISSUE TITLE
Specify output chart size in pixels

### ISSUE THREAD

**Issue by RussellPolitzky** [fslaborg/FsLab#91]
Would be helpful if it were possible to specify the size of output
charts since the default chart size may be too small in some
cases, such as the one shown below, for example.

The code specifies the chart size as 1000x1000 pixels
but the actual output from FsLab uses the default size.

I've added  a suggested syntax below.

    (*** define-output:chart(1000,1000) ***)
    Figure(Data.From [trace], layout)
    (*** include-it:chart ***)

![smallchart](https://cloud.githubusercontent.com/assets/568625/8475182/5a4e2ca4-20b6-11e5-9bcf-ac236b8d5355.PNG)

**Comment by TahaHachana** [comment]
The FsLab bootstrapping script adds an FSI printer that [overrides the width and height attributes that you specify](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.fsx#L105). You can change the default values or comment them out and specify the size when creating charts.

**Comment by tpetricek** [comment]
This is silly, I don't know why I added that code :-) if someone can send a PR removing that, I'd release a new version that does not do this ASAP.

What are the default sizes used by XPlot if nothing is explicitly specified?

**Comment by TahaHachana** [comment]
The defaults are 500 for the height and 900 for the width.

**Comment by tpetricek** [comment]
That sounds good, I think we should just remove that code from FsLab!

**Comment by RussellPolitzky** [comment]
The suggested fix seems to work with output from the FSI (ie. when executed in the context of the FSI itself) but not with rendered, journal output.

It looks like Formatter.fs sets the width and height to [600](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.Runner/Formatters.fs#L233) and [300](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.Runner/Formatters.fs#L233) pixels respectively.  Removing this gets me a 900 by 500 chart as mentioned above, rather than a 1000x1000 pixel chart in the journal output.  For some reason the explicitly specified width and height seems to be being over-ridden.  If I open the [result](https://plot.ly/~russellpolitzky/1366) in Plotly I do however see something which looks correct.

Regardless, removing the explicit width and height settings from both the FsLab bootstrapping script and Formatter.fs seems to be an improvement for Plotly charts.

**Comment by TahaHachana** [comment]
@RussellPolitzky You need to set the width and height of the figure object (besides the layout).

**Comment by RussellPolitzky** [comment]
Thanks @TahaHachana, that works.  
@tpetricek I've sent a pull request for this.

BTW, thanks to all for the work on FsLab and related projects such as XPlot.  
It's a pleasure to be able to combine:

1. a powerful, strongly typed functional programming language,
2. the low friction and rapid development of scripting with a REPL,
3. literate programming,
4. a familiar platform,
5. and high quality tools.

**Comment by tpetricek** [comment]
Closed via #93

**Comment by tpetricek** [comment]
BTW, I have to agree - XPlot is pretty amazing :)
